FROM node:18-alpine as build-stage

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

ADD config ./config
ADD public ./public
ADD scripts ./scripts
ADD src ./src

RUN npm run build

FROM caddy:2.8.4-alpine
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build-stage /app/build /www
