services:
  web:
    build: ./client
    restart: always
    depends_on:
      service:
        condition: service_started
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8345:8345"
  service:
    build: ./service
    restart: always
    environment:
      - NODE_ENV=compose
    depends_on:
      database:
        condition: service_started
    ports:
      - "3001:3001"
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

volumes:
  caddy_data:
  caddy_config:
