const MESSAGE_ACTIONS = {
    PEER_JOINED: 'PEER_JOINED',
    SIGNAL: 'SIGNAL',
    ROOM_UPDATE: 'ROOM_UPDATE',
    ROOM_UPDATE_REQUEST: 'ROOM_UPDATE_REQUEST',
    DISPLAY_NAME_UPDATE: 'DISPLAY_NAME_UPDATE',
    INSTRUMENT_UPDATE: 'INSTRUMENT_UPDATE',
    KEY_DOWN: 'KEY_DOWN',
    KEY_UP: 'KEY_UP',
    CONNECTION_UPDATE: 'CONNECTION_UPDATE',
};

export default MESSAGE_ACTIONS;
